site_name: iters
site_author: nekitdev
site_description: Composable external iteration.

repo_name: nekitdev/iters
repo_url: https://github.com/nekitdev/iters

remote_branch: github-pages

nav:
  - Index: "index.md"
  - Predicates: "predicates.md"
  - Reference:
    - Iterators: "reference/iters.md"
    - Async Iterators: "reference/async_iters.md"
    - Ordered Set: "reference/ordered_set.md"
    - Utilities: "reference/utils.md"
    - Async Utilities: "reference/async_utils.md"
    - Mappings: "reference/mappings.md"
    - Types: "reference/types.md"
    - Typing: "reference/typing.md"
  - Changelog: "changelog.md"
  - Security: "security.md"
  - Code of Conduct: "code_of_conduct.md"
  - Contributing: "contributing.md"

watch:
  - docs
  - iters

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate

      primary: deep purple
      accent: light blue

      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

    - media: "(prefers-color-scheme: light)"
      scheme: default

      primary: light blue
      accent: deep purple

      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

plugins:
  - search

  - mkdocstrings:
      handlers:
        python:
          options:
            members_order: source
            show_signature_annotations: true

          paths: [iters]

          import:
            - https://docs.python.org/3/objects.inv
            - https://nekitdev.github.io/wraps/objects.inv

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - js/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
